yolo_model:
  config_file:
    name: yolov3-luats.cfg
  weight_file:
    name: yolov3-luats_14000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - airconditioner
      - onlight
      - offlight
      - smokecensor
      - sign
      - loudspeaker
      - port
